Refactor DB: add entities, add migrations
Kutsakh/Studle pull request #17
Opened 2021-04-06 20:50 UTC by YuliaYur

Close #9

2021-04-06 20:51 UTC, Kutsakh approved these changes

2021-04-07 13:14 UTC, rostyk-begey requested changes

2021-04-07 13:14 UTC, rostyk-begey commented on Studle.BLL/Infrastructure/ServiceModule.cs
>              // Bind<ISubjectService>().To<SubjectService>().InSingletonScope();
Please remove unused code

2021-04-07 13:14 UTC, rostyk-begey commented on Studle.BLL/Services/UserService.cs
> +    */
Please remove unused file

2021-04-07 13:28 UTC, rostyk-begey approved these changes

2021-04-07 13:30 UTC, merged