added content
Kutsakh/Studle pull request #20
Opened 2021-04-11 21:24 UTC by alina26

![image](https://user-images.githubusercontent.com/43728004/114321748-054d9d80-9b25-11eb-931b-5ad636098016.png)
![image](https://user-images.githubusercontent.com/43728004/114321760-15fe1380-9b25-11eb-9304-82a529e59a68.png)

2021-04-12 10:00 UTC, rostyk-begey commented
Good job. Please also think of updating the header to contain relevant data.

2021-04-12 10:01 UTC, rostyk-begey requested changes
Good job. Please also think of updating the header to contain relevant data.

2021-04-14 19:39 UTC, alina26 commented
> Good job. Please also think of updating the header to contain relevant data.

![image](https://user-images.githubusercontent.com/43728004/114768943-31119300-9d72-11eb-9d8e-dfb3b6e11c79.png)

2021-04-15 09:24 UTC, YuliaYur approved these changes

2021-04-15 11:26 UTC, rostyk-begey approved these changes

2021-04-15 12:56 UTC, merged