Feature/auth
Kutsakh/Studle pull request #24
Opened 2021-05-04 14:46 UTC by alina26

2021-05-04 19:58 UTC, YuliaYur approved these changes

2021-05-05 11:53 UTC, rostyk-begey requested changes
Please do not delete scripts from pages. Also error message have to be shown on the same page where the form have been submited from.

2021-05-05 11:53 UTC, rostyk-begey commented on Studle.BLL/Services/UserService.cs
> +            /*Log.Information($"GUID value is: {Guid.NewGuid().ToString()}");
Please remove unused code

2021-05-05 11:53 UTC, rostyk-begey commented on Studle.BLL/Services/UserService.cs
> +            else Log.Warning($"Email isn`t available: {0} ", user.Email);
There is no need to else statement here

2021-05-05 11:53 UTC, rostyk-begey commented on Studle.DAL/EF/AppDbContext.cs
> +            Database.EnsureDeleted();   // удаляем бд со старой схемой
Please remove comments

2021-05-05 11:53 UTC, rostyk-begey commented on Studle.WEB/Controllers/SignInController.cs
> +                else
There is no need for else statement here

2021-05-05 11:53 UTC, rostyk-begey commented on Studle.BLL/DTO/RoleDto.cs
> +    class RoleDto
Please update file & class name in the same style as others

2021-05-05 11:53 UTC, rostyk-begey commented on Studle.DAL/EF/AppDbContext.cs
> +
Please remove extra linebreak

2021-05-05 11:53 UTC, rostyk-begey commented on Studle.WEB/Views/SignIn/Index.cshtml
> -@section Scripts {
Scripts shouldn't be deleted

2021-05-05 11:53 UTC, rostyk-begey commented on Studle.WEB/Views/SignUp/Index.cshtml
> -@section Scripts {
Scripts shouldn't be deleted

2021-05-05 11:53 UTC, rostyk-begey commented on Studle.WEB/Controllers/SignInController.cs
> +                return this.Redirect("/Home/Index");
Should redirect back to SignIn page with error message shown

2021-05-05 11:53 UTC, rostyk-begey commented on Studle.WEB/Controllers/SignUpController.cs
> +                return this.Redirect("/Home/Index");
Should redirect back to SignUp page with error message shown

2021-05-12 18:58 UTC, Kutsakh approved these changes

2021-05-13 10:32 UTC, rostyk-begey approved these changes

2021-05-13 10:32 UTC, merged